# CryptoRun Benchmark Configuration
# Controls benchmarking behavior against external references

# Top Gainers Benchmark Configuration
topgainers:
  # Cache TTL (minimum 300s to respect rate limits)
  ttl: 300s
  
  # Maximum number of top gainers to fetch per window
  limit: 20
  
  # Time windows to analyze (valid: 1h, 24h, 7d)
  windows:
    - "1h"
    - "24h" 
    - "7d"
  
  # Output directory for benchmark artifacts
  output_dir: "out/bench"
  
  # Audit directory for progress traces  
  audit_dir: "out/audit"

# Scoring Configuration
scoring:
  # Composite score weights (must sum to 1.0)
  weights:
    symbol_overlap: 0.6      # Weight for symbol overlap (Jaccard similarity)
    rank_correlation: 0.3    # Weight for rank correlation (Spearman-like)
    percentage_align: 0.1    # Weight for percentage alignment (future)
  
  # Alignment thresholds for interpretation
  thresholds:
    high_alignment: 0.7      # >70% = High alignment
    medium_alignment: 0.3    # 30-70% = Medium alignment
                             # <30% = Low alignment

# Rate Limiting & API Compliance
api:
  # CoinGecko API constraints
  coingecko:
    requests_per_minute: 10  # Free tier limit
    requests_per_month: 10000 # Monthly budget
    base_url: "https://api.coingecko.com/api/v3"
    timeout: 30s
    user_agent: "CryptoRun/v3.2.1 Benchmark"
    
  # Cache behavior
  cache:
    enabled: true
    directory: "out/bench/.cache"
    cleanup_after: 24h       # Clean up old cache files
    
# Progress Streaming
progress:
  # Default progress mode for benchmarks
  default_mode: "auto"      # auto|plain|json
  
  # Progress phases and their target percentages
  phases:
    init: 10                # 0-10%: Initialization
    fetch: 50               # 10-50%: Data fetching  
    analyze: 70             # 50-70%: Analysis
    score: 90               # 70-90%: Scoring
    output: 100             # 90-100%: Output generation
    
# Output Configuration
output:
  # File formats to generate
  formats:
    json: true              # JSON results for programmatic use
    markdown: true          # Markdown reports for human reading
    csv: false              # CSV exports (future)
    
  # Include detailed breakdowns
  include_details: true
  
  # Artifact retention
  retention:
    keep_individual_windows: true  # Keep per-window JSON files
    keep_cache_files: true         # Retain cache for debugging
    cleanup_after_days: 30         # Clean up old artifacts

# Integration Settings
integration:
  # Whether to trigger actual scans or use mock data
  use_live_scans: false     # true = trigger momentum scans, false = use mock data
  
  # Scan parameters when using live scans
  scan_config:
    max_sample: 20
    venues: ["kraken", "okx", "coinbase"]
    regime: "bull"
    
  # Mock data behavior
  mock_data:
    realistic_percentages: true    # Generate realistic gain percentages
    overlap_ratio: 0.45            # Target overlap ratio for testing
    
# Validation Rules
validation:
  # Minimum cache TTL enforcement
  min_ttl_seconds: 300
  
  # Valid time windows
  valid_windows: ["1h", "24h", "7d"]
  
  # Maximum limits to prevent excessive API usage
  max_limit: 100
  
  # Required fields for composite scoring
  required_score_weights: ["symbol_overlap", "rank_correlation", "percentage_align"]