regime_detector:
  update_frequency: 4h
  indicators:
    realized_vol_7d: 0.4
    percent_above_20ma: 0.3
    breadth_thrust: 0.3
  thresholds:
    trending_bull:
      vol_max: 0.3
      above_ma_min: 0.6
      thrust_min: 0.4
    choppy:
      vol_min: 0.3
      vol_max: 0.5
      above_ma_range: [0.4, 0.6]
      thrust_range: [0.2, 0.4]
    high_volatility:
      vol_min: 0.5
