database:
  enabled: false  # Set to true to enable database persistence
  dsn: ""  # PostgreSQL connection string - can also be set via PG_DSN env var
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "30m"
  conn_max_idle_time: "5m"
  query_timeout: "30s"

# Example DSN formats:
# Development: "postgres://username:password@localhost:5432/cryptorun?sslmode=disable"
# Production: "postgres://username:password@db.example.com:5432/cryptorun?sslmode=require"
# TimescaleDB: "postgres://username:password@timescale.example.com:5432/cryptorun?sslmode=require"

# Environment variable overrides (takes precedence over YAML):
# PG_ENABLED=true
# PG_DSN=postgres://user:pass@localhost:5432/cryptorun?sslmode=disable
# PG_MAX_OPEN_CONNS=20
# PG_MAX_IDLE_CONNS=10
# PG_CONN_MAX_LIFETIME=1h
# PG_CONN_MAX_IDLE_TIME=10m
# PG_QUERY_TIMEOUT=1m