# Pre-Movement Detector v3.3 Configuration
# Coiled-spring setup detection with 100-point composite scoring

# Data freshness and health monitoring
freshness:
  hard_fail_s: 90        # Hard failure threshold - 90 seconds max staleness
  soft_warn_s: 30        # Soft warning threshold for UI indicators
  worst_feed_wins: true  # Use worst (stalest) feed for health decisions
  decay_half_life_s: 45  # Half-life for freshness penalties

# Scoring model (100-point composite)
scoring:
  structural_weight: 45    # Structural indicators (45 points)
  behavioral_weight: 30    # Behavioral flow analysis (30 points)
  catalyst_compression_weight: 25  # Catalyst/compression signals (25 points)
  
  # Score thresholds
  min_composite_score: 60  # Minimum score for consideration
  strong_signal_score: 75  # Strong signal threshold
  exceptional_score: 85    # Exceptional opportunity threshold

# 2-of-3 Gates system
gates:
  required_gates: 2        # Must pass 2 of 3 gates minimum
  volume_gate_regime_override: true  # Volume gate can override in certain regimes
  
  # Individual gate thresholds
  microstructure:
    min_depth_pct: 2.0     # ±2% depth requirement
    max_spread_bps: 50     # Max spread 50 basis points
    min_bid_ask_ratio: 0.8 # Min bid/ask size ratio
  
  volume:
    min_surge_multiple: 1.75  # Volume surge threshold
    min_adv_coverage: 0.3     # ADV coverage requirement
  
  momentum:
    min_acceleration: 0.02    # Minimum momentum acceleration
    max_fatigue_rsi: 70      # RSI fatigue threshold

# Portfolio construction and risk management
portfolio:
  max_correlation: 0.65    # Maximum correlation between positions
  max_per_sector: 2        # Maximum positions per sector
  beta_budget: 15.0        # Total beta budget limit
  
  # Correlation matrix settings
  lookback_1h: 168         # 1-hour correlation lookback (7 days)
  lookback_4h: 168         # 4-hour correlation lookback (28 days)
  min_observations: 50     # Minimum observations for correlation
  
  # Sector classification
  sectors:
    - "DeFi"
    - "Layer1"
    - "Layer2"
    - "Gaming"
    - "AI/ML"
    - "Infrastructure"
    - "Payments"
    - "Privacy"
    - "Meme"
    - "Other"

# Alert system configuration
alerts:
  rate_limits:
    per_hour: 3           # Maximum 3 alerts per hour
    per_day: 10           # Maximum 10 alerts per day
    volatility_allowance: 2  # Extra alerts during high volatility
  
  # Manual override settings
  manual_override:
    alert_only_mode: true  # Manual override only shows alerts, no auto-execution
    override_duration_s: 3600  # Override lasts 1 hour
    max_overrides_per_day: 5   # Maximum manual overrides per day

# Execution quality monitoring
execution_quality:
  slippage_tracking: true
  target_fill_time_ms: 5000   # Target fill time 5 seconds
  max_acceptable_slippage_bps: 25  # 25 basis points max slippage
  
  # Recovery settings after poor execution
  recovery_cooldown_s: 300    # 5-minute cooldown after poor execution
  max_consecutive_fails: 3    # Max consecutive execution failures

# Learning and backtesting system
learning:
  enable_pit_replay: true     # Enable point-in-time replay
  hit_rate_tracking: true     # Track hit rates by setup type
  isotonic_calibration: true  # Enable probability calibration
  
  # Backtest settings
  lookback_days: 90          # 90-day backtest window
  min_samples_per_bin: 10    # Minimum samples for calibration bins
  rebalance_frequency_h: 24  # Rebalance frequency (daily)

# Data sources and feeds
data_sources:
  primary_exchange: "kraken"  # Primary data source
  backup_exchanges: ["binance", "coinbase"]  # Backup exchanges
  
  # WebSocket settings
  ws_reconnect_delay_s: 5    # Reconnection delay
  ws_max_reconnects: 10      # Maximum reconnection attempts
  
  # REST fallback
  rest_poll_interval_s: 15   # REST polling interval when WS fails
  rest_timeout_s: 10         # REST request timeout

# UI refresh and SSE configuration
ui:
  max_refresh_hz: 1.0        # Maximum UI refresh rate (1 Hz)
  sse_enabled: true          # Enable Server-Sent Events
  sse_heartbeat_s: 30        # SSE heartbeat interval
  
  # Board display settings
  top_n_display: 20          # Show top 20 opportunities on board
  auto_scroll: true          # Auto-scroll to new opportunities
  sound_alerts: false        # Audio alerts disabled by default

# System health and monitoring
health:
  metrics_export: true       # Export Prometheus metrics
  artifact_retention_days: 30  # Keep artifacts for 30 days
  log_level: "info"          # Logging level
  
  # Performance thresholds
  max_processing_time_ms: 1000  # Max processing time per cycle
  max_memory_mb: 512            # Memory usage limit
  
# Circuit breaker configuration
circuit_breakers:
  api_failure_threshold: 5      # API failure threshold
  api_recovery_time_s: 60       # API recovery time
  data_staleness_circuit_s: 180 # Circuit opens if data >3min stale

# Regime-specific adjustments
regime_adjustments:
  trending_bull:
    structural_boost: 1.1      # 10% boost to structural weight
    catalyst_boost: 0.9        # 10% reduction to catalyst weight
    gate_relaxation: 0.05      # Slightly relax gate thresholds
  
  choppy:
    behavioral_boost: 1.2      # 20% boost to behavioral weight
    structural_reduction: 0.9  # 10% reduction to structural weight
    gate_tightening: 0.1       # Tighten gate thresholds
  
  high_vol:
    catalyst_boost: 1.3        # 30% boost to catalyst weight
    all_gates_required: true   # Require all 3 gates in high vol