apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptorun
  namespace: cryptorun-staging
spec:
  template:
    spec:
      containers:
      - name: cryptorun
        env:
        - name: ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 500Mi
          limits:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 1Gi
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15