name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: |
          cd src
          go build ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m
      - name: Test
        run: |
          cd src
          go test ./...
