apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cryptorun

resources:
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../configmap.yaml
  - ../../secret.yaml
  - ../../ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

commonLabels:
  environment: production
  
images:
  - name: cryptorun
    newTag: v3.2.1

replicas:
  - name: cryptorun
    count: 3