name: crypto-run-ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: go mod tidy
      - run: go vet ./...
      - run: go test ./...
      - run: go build ./...