name: crypto-run-ci
on: [push, pull_request]
jobs:
  qa-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run No-TODO QA Gate
        run: |
          chmod +x scripts/qa/no_todo.sh
          scripts/qa/no_todo.sh
      - name: Upload QA Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: qa-report
          path: no_todo_report.txt
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: qa-gate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: go mod tidy
      - run: go vet ./...
      - run: go test ./...
      - name: Load Testing
        run: go test ./... -tags=load -timeout=10m
      - run: go build ./...
      
  security-scan:
    runs-on: ubuntu-latest
    needs: qa-gate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for secret scanning
      
      # Secret scanning with gitleaks
      - name: Run gitleaks secret scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          config-path: .gitleaks.toml
      
      # Vulnerability scanning with Trivy
      - name: Run Trivy filesystem vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'  # Fail on HIGH/CRITICAL vulnerabilities
      
      - name: Upload Trivy filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()  # Upload even if scan fails
        with:
          sarif_file: 'trivy-fs-results.sarif'
      
      # Docker configuration scanning
      - name: Run Trivy Docker configuration scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'  # Don't fail on config issues, just report
      
      # Build Docker image for container scanning
      - name: Build Docker image for scanning
        run: docker build -t cryptorun:ci-scan .
      
      # Container image scanning
      - name: Run Trivy container image scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cryptorun:ci-scan'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'  # Fail on HIGH/CRITICAL vulnerabilities in image
      
      - name: Upload Trivy image scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'
      
      # Kubernetes security scanning
      - name: Run Trivy Kubernetes manifests scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'deploy/k8s/'
          format: 'table'
          severity: 'MEDIUM,HIGH,CRITICAL'
          exit-code: '0'  # Report but don't fail
      
      # SAST (Static Application Security Testing) with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:go"
      
      # Generate security report
      - name: Generate Security Report
        if: always()
        run: |
          echo "# Security Scan Report" > security-report.md
          echo "Generated at: $(date)" >> security-report.md
          echo "" >> security-report.md
          echo "## Scans Performed" >> security-report.md
          echo "- [x] Secret scanning (gitleaks)" >> security-report.md
          echo "- [x] Filesystem vulnerability scanning (Trivy)" >> security-report.md
          echo "- [x] Docker configuration scanning (Trivy)" >> security-report.md
          echo "- [x] Container image scanning (Trivy)" >> security-report.md
          echo "- [x] Kubernetes manifest scanning (Trivy)" >> security-report.md
          echo "- [x] SAST scanning (CodeQL)" >> security-report.md
          echo "" >> security-report.md
          echo "## Summary" >> security-report.md
          echo "See uploaded SARIF files and workflow logs for detailed results." >> security-report.md
      
      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: |
            security-report.md
            trivy-*.sarif
          retention-days: 30