name: Nightly Analyst Coverage
on:
  schedule:
    - cron: '7 * * * *'
  workflow_dispatch: {}
jobs:
  analyst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p out/analyst out/scanner
      - run: |
          if [ ! -f out/scanner/latest_candidates.jsonl ]; then
            echo '{"symbol":"SOLUSD","venue":"KRAKEN","ts_decision":"2025-09-05T10:00:02Z","score_components":{"MomentumCore":67.4},"gates":{"freshness":{"ok":true,"age_bars":1}},"composite":84.0,"selected":true}' > out/scanner/latest_candidates.jsonl
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: analyst
          path: out/analyst/*
