name: CryptoRun PR Quality
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - run: go build -tags no_net ./...
      - run: go test ./... -count=1
      - name: Python tests
        if: hashFiles('pytest.ini', 'pyproject.toml') != ''
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pytest -q
        if: hashFiles('pytest.ini', 'pyproject.toml') != ''
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
